

IF (CAIRO_INCLUDE_DIRS AND CAIRO_LIBRARIES)
    SET(CAIRO_FOUND TRUE)
ELSE (CAIRO_INCLUDE_DIRS AND CAIRO_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_CAIRO_PC QUIET cairo)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (CAIRO_INCLUDE_DIRS cairo.h 
        ${_CAIRO_PC_INCLUDE_DIRS})

    FIND_LIBRARY (CAIRO_LIBRARIES NAMES cairo
        PATH ${_CAIRO_PC_LIBDIR})

    IF (CAIRO_INCLUDE_DIRS AND CAIRO_LIBRARIES)
        SET(CAIRO_FOUND TRUE)
    ENDIF (CAIRO_INCLUDE_DIRS AND CAIRO_LIBRARIES)

    IF (CAIRO_FOUND)
        IF (NOT CAIRO_FIND_QUIETLY)
            MESSAGE (STATUS "Found cairo : ${CAIRO_LIBRARIES}")
        ENDIF (NOT CAIRO_FIND_QUIETLY)
    ELSE (CAIRO_FOUND)
        IF (NOT CAIRO_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find cairo")
        ENDIF (NOT CAIRO_FIND_QUIETLY)
    ENDIF (CAIRO_FOUND)

    MARK_AS_ADVANCED(CAIRO_INCLUDE_DIRS CAIRO_LIBRARIES)

ENDIF (CAIRO_INCLUDE_DIRS AND CAIRO_LIBRARIES)
