
IF (LIBDRM_INCLUDE_DIRS AND LIBDRM_LIBRARIES)
    SET(LIBDRM_FOUND TRUE)
ELSE (LIBDRM_INCLUDE_DIRS AND LIBDRM_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_LIBDRM_PC QUIET libdrm)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (LIBDRM_INCLUDE_DIRS drm.h 
        ${_LIBDRM_PC_INCLUDE_DIRS})

    FIND_LIBRARY (LIBDRM_LIBRARIES NAMES drm
        PATH ${_LIBDRM_PC_LIBDIR})

    IF (LIBDRM_INCLUDE_DIRS AND LIBDRM_LIBRARIES)
        SET(LIBDRM_FOUND TRUE)
    ENDIF (LIBDRM_INCLUDE_DIRS AND LIBDRM_LIBRARIES)

    IF (LIBDRM_FOUND)
        IF (NOT LIBDRM_FIND_QUIETLY)
            MESSAGE (STATUS "Found libdrm : ${LIBDRM_LIBRARIES}")
        ENDIF (NOT LIBDRM_FIND_QUIETLY)
    ELSE (LIBDRM_FOUND)
        IF (NOT LIBDRM_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find libdrm")
        ENDIF (NOT LIBDRM_FIND_QUIETLY)
    ENDIF (LIBDRM_FOUND)

    MARK_AS_ADVANCED(LIBDRM_INCLUDE_DIRS LIBDRM_LIBRARIES)

ENDIF (LIBDRM_INCLUDE_DIRS AND LIBDRM_LIBRARIES)
