

IF (LIBINPUT_INCLUDE_DIRS AND LIBINPUT_LIBRARIES)
    SET(LIBINPUT_FOUND TRUE)
ELSE (LIBINPUT_INCLUDE_DIRS AND LIBINPUT_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_LIBINPUT_PC QUIET libinput)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (LIBINPUT_INCLUDE_DIRS libinput.h 
        ${_LIBINPUT_PC_INCLUDE_DIRS})

    FIND_LIBRARY (LIBINPUT_LIBRARIES NAMES input
        PATH ${_LIBINPUT_PC_LIBDIR})

    IF (LIBINPUT_INCLUDE_DIRS AND LIBINPUT_LIBRARIES)
        SET(LIBINPUT_FOUND TRUE)
    ENDIF (LIBINPUT_INCLUDE_DIRS AND LIBINPUT_LIBRARIES)

    IF (LIBINPUT_FOUND)
        IF (NOT LIBINPUT_FIND_QUIETLY)
            MESSAGE (STATUS "Found libinput : ${LIBINPUT_LIBRARIES}")
        ENDIF (NOT LIBINPUT_FIND_QUIETLY)
    ELSE (LIBINPUT_FOUND)
        IF (NOT LIBINPUT_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find libinput")
        ENDIF (NOT LIBINPUT_FIND_QUIETLY)
    ENDIF (LIBINPUT_FOUND)

    MARK_AS_ADVANCED(LIBINPUT_INCLUDE_DIRS LIBINPUT_LIBRARIES)

ENDIF (LIBINPUT_INCLUDE_DIRS AND LIBINPUT_LIBRARIES)
