
IF (XKBCOMMON_INCLUDE_DIRS AND XKBCOMMON_LIBRARIES)
    SET(XKBCOMMON_FOUND TRUE)
ELSE (XKBCOMMON_INCLUDE_DIRS AND XKBCOMMON_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_XKBCOMMON_PC QUIET xkbcommon)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (XKBCOMMON_INCLUDE_DIRS xkbcommon/xkbcommon.h 
        HINTS ${_XKBCOMMON_PC_INCLUDE_DIRS})

    FIND_LIBRARY (XKBCOMMON_LIBRARIES NAMES xkbcommon
        PATH ${_XKBCOMMON_PC_LIBDIR})

    IF (XKBCOMMON_INCLUDE_DIRS AND XKBCOMMON_LIBRARIES)
        SET(XKBCOMMON_FOUND TRUE)
    ENDIF (XKBCOMMON_INCLUDE_DIRS AND XKBCOMMON_LIBRARIES)

    IF (XKBCOMMON_FOUND)
        IF (NOT XKBCOMMON_FIND_QUIETLY)
            MESSAGE (STATUS "Found xkbcommon : ${XKBCOMMON_LIBRARIES}")
        ENDIF (NOT XKBCOMMON_FIND_QUIETLY)
    ELSE (XKBCOMMON_FOUND)
        IF (NOT XKBCOMMON_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find xkbcommon")
        ENDIF (NOT XKBCOMMON_FIND_QUIETLY)
    ENDIF (XKBCOMMON_FOUND)

    MARK_AS_ADVANCED(XKBCOMMON_INCLUDE_DIRS XKBCOMMON_LIBRARIES)

ENDIF (XKBCOMMON_INCLUDE_DIRS AND XKBCOMMON_LIBRARIES)
