
IF (EGL_INCLUDE_DIRS AND EGL_LIBRARIES)
    SET(EGL_FOUND TRUE)
ELSE (EGL_INCLUDE_DIRS AND EGL_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_EGL_PC QUIET egl)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (EGL_INCLUDE_DIRS EGL 
        ${_EGL_PC_INCLUDE_DIRS})

    FIND_LIBRARY (EGL_LIBRARIES NAMES EGL
        PATH ${_EGL_PC_LIBDIR})

    IF (EGL_INCLUDE_DIRS AND EGL_LIBRARIES)
        SET(EGL_FOUND TRUE)
    ENDIF (EGL_INCLUDE_DIRS AND EGL_LIBRARIES)

    IF (EGL_FOUND)
        IF (NOT EGL_FIND_QUIETLY)
            MESSAGE (STATUS "Found EGL : ${EGL_LIBRARIES}")
        ENDIF (NOT EGL_FIND_QUIETLY)
    ELSE (EGL_FOUND)
        IF (NOT EGL_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find EGl")
        ENDIF (NOT EGL_FIND_QUIETLY)
    ENDIF (EGL_FOUND)

    MARK_AS_ADVANCED(EGL_INCLUDE_DIRS EGL_LIBRARIES)

ENDIF (EGL_INCLUDE_DIRS AND EGL_LIBRARIES)
