
IF (LIBUDEV_INCLUDE_DIRS AND LIBUDEV_LIBRARIES)
    SET(LIBUDEV_FOUND TRUE)
ELSE (LIBUDEV_INCLUDE_DIRS AND LIBUDEV_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_LIBUDEV_PC QUIET udev)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)

    FIND_PATH (LIBUDEV_INCLUDE_DIRS libudev.h 
        ${_LIBUDEV_PC_INCLUDE_DIRS})

    FIND_LIBRARY (LIBUDEV_LIBRARIES NAMES udev
        PATH ${_LIBUDEV_PC_LIBDIR})

    IF (LIBUDEV_INCLUDE_DIRS AND LIBUDEV_LIBRARIES)
        SET(LIBUDEV_FOUND TRUE)
    ENDIF (LIBUDEV_INCLUDE_DIRS AND LIBUDEV_LIBRARIES)

    IF (LIBUDEV_FOUND)
        IF (NOT LIBUDEV_FIND_QUIETLY)
            MESSAGE (STATUS "Found udev : ${LIBUDEV_LIBRARIES}")
        ENDIF (NOT LIBUDEV_FIND_QUIETLY)
    ELSE (LIBUDEV_FOUND)
        IF (NOT LIBUDEV_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find udev")
        ENDIF (NOT LIBUDEV_FIND_QUIETLY)
    ENDIF (LIBUDEV_FOUND)

    MARK_AS_ADVANCED(LIBUDEV_INCLUDE_DIRS LIBUDEV_LIBRARIES)

ENDIF (LIBUDEV_INCLUDE_DIRS AND LIBUDEV_LIBRARIES)
