
IF (PANGOCAIRO_INCLUDE_DIRS AND PANGOCAIRO_LIBRARIES)
    SET(PANGOCAIRO_FOUND TRUE)
ELSE (PANGOCAIRO_INCLUDE_DIRS AND PANGOCAIRO_LIBRARIES)
    IF (NOT WIN32)
        FIND_PACKAGE (PkgConfig)
        IF (PKG_CONFIG_FOUND)
            pkg_check_modules(_PANGOCAIRO_PC QUIET pangocairo)
        ENDIF (PKG_CONFIG_FOUND)
    ENDIF (NOT WIN32)


    FIND_PATH (PANGOCAIRO_INCLUDE_DIRS pango
        HINTS ${_PANGOCAIRO_PC_INCLUDE_DIR} ${_PANGOCAIRO_PC_INCLUDE_DIRS})


    #    FIND_LIBRARY (PANGOCAIRO_LIBRARIES NAMES 
    #   pangocairo-1.0 libpangocairo-1.0
    #    HINTS ${_PANGOCAIRO_PC_LIBDIR} ${_PANGOCAIRO_PC_LIBDIRS})
    
    set (PANGOCAIRO_INCLUDE_DIRS ${_PANGOCAIRO_PC_INCLUDE_DIRS})
    set (PANGOCAIRO_LIBRARIES ${_PANGOCAIRO_PC_LIBRARIES})

    message ("PANGOCAIRO : ${_PANGOCAIRO_PC_LIBRARIES}")

    IF (PANGOCAIRO_INCLUDE_DIRS AND PANGOCAIRO_LIBRARIES)
        SET(PANGOCAIRO_FOUND TRUE)
    ENDIF (PANGOCAIRO_INCLUDE_DIRS AND PANGOCAIRO_LIBRARIES)

    IF (PANGOCAIRO_FOUND)
        IF (NOT PANGOCAIRO_FIND_QUIETLY)
            MESSAGE (STATUS "Found pangocairo : ${PANGOCAIRO_LIBRARIES}")
        ENDIF (NOT PANGOCAIRO_FIND_QUIETLY)
    ELSE (PANGOCAIRO_FOUND)
        IF (NOT PANGOCAIRO_FIND_QUIETLY)
            MESSAGE (FATAL_ERROR "Could NOT find pangocairo")
        ENDIF (NOT PANGOCAIRO_FIND_QUIETLY)
    ENDIF (PANGOCAIRO_FOUND)

    MARK_AS_ADVANCED(PANGOCAIRO_INCLUDE_DIRS PANGOCAIRO_LIBRARIES)

ENDIF (PANGOCAIRO_INCLUDE_DIRS AND PANGOCAIRO_LIBRARIES)
